# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
