# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20190624_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_user',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
