# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-24 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_profile_new_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='new_user',
            new_name='new_username',
        ),
    ]
